# Generated by Django 3.0 on 2019-12-13 09:19

from django.db import migrations, models
import django.db.models.deletion
import rekita_lessons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rekita_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePanel',
            fields=[
                ('key_code', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rekita_users.Lesson')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekita_users.Master')),
                ('students', models.ManyToManyField(to='rekita_users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('dead_line', models.DateTimeField(default=rekita_lessons.models.default_deadline)),
                ('attach', models.FileField(upload_to=rekita_lessons.models.directory)),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekita_lessons.CoursePanel')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='exercises', to='rekita_users.Master')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=rekita_lessons.models.directory_res)),
                ('description', models.TextField(max_length=5000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekita_users.Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekita_lessons.Task')),
            ],
        ),
    ]
