# Generated by Django 3.0 on 2019-12-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekita_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='level',
            field=models.CharField(choices=[('bs', 'bachlor'), ('ms', 'master'), ('dr', 'doctorate')], max_length=25),
        ),
    ]
